In [12]:
import pandas as pd
df = pd.read_csv('databases\dataset2001_2024.csv')
df

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\natan\AppData\Local\Temp\ipykernel_14600\482236970.py:2: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv('databases\dataset2001_2024.csv')

,YEAR,MO,DY,HR,ALLSKY_SFC_UV_INDEX,ALLSKY_SRF_ALB,CLRSKY_KT,CLOUD_AMT,T2M,PS,PW,WD10M,WD50M,WS50M,WS10M,TOA_SW_DNI,QV2M,QV10M
0,2001,1,1,0,0.00,-999.00,-999.00,32.70,18.93,93.39,2.72,140.07,139.57,6.24,4.25,0.00,13.79,13.73
1,2001,1,1,1,0.00,-999.00,-999.00,24.88,18.54,93.40,2.66,138.43,137.82,6.18,4.06,0.00,13.55,13.49
2,2001,1,1,2,0.00,-999.00,-999.00,51.42,18.21,93.36,2.61,138.09,137.45,6.08,3.89,0.00,13.37,13.31
3,2001,1,1,3,0.00,-999.00,-999.00,66.36,17.94,93.31,2.55,137.70,136.99,5.89,3.63,0.00,13.18,13.18
4,2001,1,1,4,0.00,-999.00,-999.00,51.16,17.69,93.27,2.50,137.93,137.20,5.62,3.35,0.00,13.06,13.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201595,2023,12,31,19,2.92,0.15,0.67,31.79,28.00,93.33,2.72,155.45,154.80,6.44,5.66,1408.66,11.47,11.29
201596,2023,12,31,20,0.80,0.13,0.58,20.45,25.87,93.38,2.70,152.49,152.07,7.36,6.12,1408.61,11.72,11.66
201597,2023,12,31,21,0.05,0.16,0.38,31.40,23.62,93.45,2.70,148.69,148.45,7.88,6.21,1408.76,12.08,12.02
201598,2023,12,31,22,0.00,-999.00,-999.00,21.06,21.87,93.52,2.71,145.60,145.61,7.41,5.61,0.00,12.45,12.39
201599,2023,12,31,23,0.00,-999.00,-999.00,22.94,20.82,93.55,2.72,140.66,140.22,6.68,4.93,0.00,12.70,12.70

In [13]:
train_size = 0.8

train_data = df[:int(len(df) * train_size)]
test_data = df[int(len(df) * train_size):]

In [14]:
def create_features(series, n_lags):
    X, y = [], []
    for i in range(n_lags, len(series)):
        X.append(series[i - n_lags:i])
        y.append(series[i])
    return pd.DataFrame(X), pd.Series(y)

In [15]:
n_lags = 10

X_train, y_train = create_features(train_data['T2M'].values, n_lags)

X_test, y_test = create_features(test_data['T2M'].values, n_lags)

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

model = RandomForestRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [17]:
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error: ', mse)

Mean Squared Error:  0.18748449317439844

In [19]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(test_data.index[n_lags:], y_test, label='True Values', color='blue')
plt.plot(test_data.index[n_lags:], y_pred, label='Predict Values', color='red')
plt.title('Predicoes vs Valores reais')
plt.legend()
plt.show()

ModuleNotFoundError: No module named 'matplotlib.backends.registry'